### ISSUE TITLE
License

### ISSUE THREAD

**Issue by odow** [robin-vjc/smps#1]
Hi @robin-vjc,

I'm working on improving an SMPS reader in Julia (https://github.com/mtanneau/SMPSReader.jl/pull/5) and came across this.

Any reason why you didn't add a LICENSE to this repo? This would be useful for a project I have going: https://github.com/odow/StochOptFormat. 

You can find more information here: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

Cheers,
Oscar

**Comment by robin-vjc** [comment]
Hi Oscar,

Thanks for the request - I have added the license. Please let me know if I can be of help in any other way.

Cheers,
Robin

**Comment by odow** [comment]
Thanks!
